#!/usr/bin/env python3
"""Create synthetic fixtures and smoke-test ImageMagick operation families safely.

Every fixture is generated by ImageMagick inside --workdir; the suite never reads,
writes or lists any pre-existing user file. Each case asserts an inspectable
property of its output (geometry, colorspace, frame count, byte budget, pixel
difference) rather than trusting the exit status alone.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import shlex
import shutil
import subprocess
import sys
import time

try:
    # Written in parallel with this file; the suite must still run without it.
    from check_natural_language_cases import validate as validate_natural_language_cases
except ImportError:
    validate_natural_language_cases = None

DOWNLOAD_URL = "https://imagemagick.org/script/download.php"
# IM7 exposes these as `magick <tool>`; IM6 ships them as separate executables.
TOOLS = ("identify", "mogrify", "montage", "compare")
# h264 rejects 1x1 frames, so video needs a macroblock-sized probe to be honest.
PROBE_SIZE = {"MP4": "16x16", "MOV": "16x16", "WEBM": "16x16"}


def decode(raw: bytes) -> str:
    return raw.decode("utf-8", "replace")


def one_line(text: str, limit: int = 200) -> str:
    """Delegate errors are multi-line; a skip reason must stay greppable."""
    return " ".join(text.split())[-limit:]


def show(argv: list[str]) -> str:
    return shlex.join(str(a) for a in argv)


class Checks:
    """Collects every assertion instead of aborting on the first failure."""

    def __init__(self) -> None:
        self.passed: list[str] = []
        self.failed: list[str] = []

    def _record(self, ok: bool, text: str) -> bool:
        (self.passed if ok else self.failed).append(text)
        return ok

    def eq(self, label: str, actual: object, expected: object) -> bool:
        return self._record(actual == expected,
                            f"{label}: {actual!r}" + ("" if actual == expected else f" != expected {expected!r}"))

    def gt(self, label: str, actual: float, floor: float) -> bool:
        return self._record(actual is not None and actual > floor, f"{label}: {actual!r} > {floor!r}")

    def le(self, label: str, actual: float, ceiling: float) -> bool:
        return self._record(actual is not None and actual <= ceiling, f"{label}: {actual!r} <= {ceiling!r}")

    def near(self, label: str, actual: float, expected: float, tol: float = 1e-4) -> bool:
        return self._record(actual is not None and abs(actual - expected) <= tol,
                            f"{label}: {actual!r} ~= {expected!r} (tol {tol})")

    def true(self, label: str, ok: bool, detail: object = "") -> bool:
        return self._record(bool(ok), f"{label}: {detail}" if detail != "" else label)


class Suite:
    def __init__(self, binary: str, workdir: Path, im7: bool, verbose: bool = False):
        self.binary = binary
        self.workdir = workdir
        self.im7 = im7
        self.verbose = verbose
        self.results: list[dict[str, object]] = []
        self.tools = {name: (None if im7 else shutil.which(name)) for name in TOOLS}
        self.formats = self._list_formats()
        self.denied = self._denied_coders()
        self._probes: dict[str, tuple[bool, str]] = {}

    # ---- command construction -------------------------------------------------
    def path(self, name: str) -> Path:
        return self.workdir / name

    def convert(self, *args: object) -> list[str]:
        """IM7 `magick` and IM6 `convert` are both the convert-style entry point."""
        return [self.binary, *[str(a) for a in args]]

    def tool(self, name: str, *args: object) -> list[str]:
        if self.im7:
            return [self.binary, name, *[str(a) for a in args]]
        return [self.tools[name] or name, *[str(a) for a in args]]

    def _exec(self, argv: list[str], stdin: bytes | None = None) -> subprocess.CompletedProcess:
        return subprocess.run(argv, cwd=self.workdir, input=stdin, capture_output=True, timeout=180)

    # ---- inspection helpers ---------------------------------------------------
    def _list_formats(self) -> dict[str, str]:
        proc = self._exec(self.convert("-list", "format"))
        formats: dict[str, str] = {}
        for line in decode(proc.stdout).splitlines():
            match = re.match(r"\s+([A-Za-z0-9]+)\*?\s+[A-Za-z0-9-]+\s+([rw+-]{3,4})\s", line)
            if match:
                formats[match.group(1).upper()] = match.group(2)
        return formats

    def _denied_coders(self) -> set[str]:
        proc = self._exec(self.convert("-list", "policy"))
        denied: set[str] = set()
        pattern = None
        for raw in decode(proc.stdout).splitlines():
            line = raw.strip()
            if line.startswith("Path:"):
                pattern = None
            name = re.match(r"pattern:\s*(\S+)", line)
            if name:
                pattern = name.group(1)
            if pattern and re.match(r"rights:\s*None", line, re.IGNORECASE):
                denied.add(pattern.upper())
                pattern = None
        return denied

    def fmt(self, path: object, spec: str) -> str:
        proc = self._exec(self.tool("identify", "-format", spec, str(path)))
        if proc.returncode != 0:
            raise RuntimeError(f"identify failed on {path}: {decode(proc.stderr).strip()[-400:]}")
        return decode(proc.stdout)

    def dims(self, path: object) -> tuple[int, int]:
        width, height = self.fmt(f"{path}[0]", "%w %h").split()
        return int(width), int(height)

    def frames(self, path: object) -> int:
        return len([line for line in self.fmt(path, "%s\n").splitlines() if line.strip()])

    def max_saturation(self, path: object) -> float:
        """`%[fx:maxima.s]` is not a legal channel qualifier; separate HSL's S plane."""
        proc = self._exec(self.convert(str(path), "-colorspace", "HSL", "-channel", "G",
                                       "-separate", "-format", "%[fx:maxima]", "info:"))
        return float(decode(proc.stdout).strip())

    def compare_ae(self, left: Path, right: Path) -> float | None:
        """`compare` exits 1 when images merely differ, so read the metric, not $?."""
        proc = self._exec(self.tool("compare", "-metric", "AE", str(left), str(right), "null:"))
        text = (decode(proc.stderr) + decode(proc.stdout)).strip()
        match = re.search(r"[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?", text)
        return float(match.group(0)) if match else None

    def first_font(self) -> str | None:
        proc = self._exec(self.convert("-list", "font"))
        match = re.search(r"(?m)^\s*Font:\s*(\S+)\s*$", decode(proc.stdout))
        return match.group(1) if match else None

    # ---- capability gates -----------------------------------------------------
    def need_format(self, name: str) -> tuple[bool, str]:
        """A real encode+decode probe. `-list format` and `-version` both lie when a
        coder module is missing from disk (Homebrew leaves heic/jxl advertised but
        unloadable), and only a round-trip catches that."""
        key = name.upper()
        if key in self._probes:
            return self._probes[key]
        mode = self.formats.get(key)
        if not mode:
            result = (False, f"{key}: absent from `-list format` (coder module not installed)")
        elif "w" not in mode:
            result = (False, f"{key}: not writable, `-list format` mode is {mode}")
        elif key in self.denied:
            result = (False, f"{key}: denied by security policy (`-list policy`)")
        else:
            probe = self.path(f"_probe_{key.lower()}.{key.lower()}")
            size = PROBE_SIZE.get(key, "1x1")
            write = self._exec(self.convert("-size", size, "xc:red", str(probe)))
            if write.returncode != 0 or not probe.is_file() or probe.stat().st_size == 0:
                result = (False, f"{key}: {size} encode probe failed: {one_line(decode(write.stderr))}")
            else:
                read = self._exec(self.tool("identify", "-format", "%m", str(probe)))
                result = ((True, "") if read.returncode == 0 else
                          (False, f"{key}: decode probe failed: {one_line(decode(read.stderr))}"))
        self._probes[key] = result
        return result

    def need_helper(self, name: str, why: str) -> tuple[bool, str]:
        return (True, "") if shutil.which(name) else (False, f"{name} not on PATH; {why}")

    def need(self, ok: bool, reason: str) -> tuple[bool, str]:
        return (ok, "" if ok else reason)

    # ---- case runner ----------------------------------------------------------
    def run(self, case: str, *steps: list[object], check=None, gate: list[tuple[bool, str]] | None = None,
            expect_failure: bool = False, ok_exits: tuple[int, ...] = (0,), pipe: bool = False) -> bool:
        commands = [show([str(a) for a in step]) for step in steps]
        for ok, reason in gate or []:
            if not ok:
                self.results.append({"case": case, "command": commands, "status": "skipped", "reason": reason})
                return False

        started = time.monotonic()
        procs: list[subprocess.CompletedProcess] = []
        stdin: bytes | None = None
        for step in steps:
            proc = self._exec([str(a) for a in step], stdin=stdin)
            procs.append(proc)
            stdin = proc.stdout if pipe else None
            if proc.returncode != 0:
                break

        last = procs[-1]
        item: dict[str, object] = {
            "case": case,
            "command": commands,
            "exit": last.returncode,
            "seconds": round(time.monotonic() - started, 3),
        }
        if expect_failure:
            item["expect_failure"] = True

        checks = Checks()
        if expect_failure:
            checks.true("exits nonzero as required", last.returncode != 0, f"exit={last.returncode}")
        elif last.returncode not in ok_exits:
            checks.failed.append(f"exit {last.returncode}: {decode(last.stderr).strip()[-500:]}")
        if check and (expect_failure or last.returncode in ok_exits):
            try:
                check(checks, procs)
            except Exception as exc:  # a broken assertion is recorded, never hidden
                checks.failed.append(f"check raised: {exc}")

        item["status"] = "fail" if checks.failed else "pass"
        if checks.passed:
            item["assertions"] = checks.passed
        if checks.failed:
            item["errors"] = checks.failed
        if self.verbose or checks.failed:
            item["stdout_tail"] = decode(last.stdout)[-400:] if not pipe else f"<{len(last.stdout)} bytes>"
            item["stderr_tail"] = decode(last.stderr)[-600:]
        self.results.append(item)
        return not checks.failed

    def build(self, argv: list[object]) -> None:
        """Fixture generation must succeed; a failure here invalidates the run."""
        proc = self._exec([str(a) for a in argv])
        if proc.returncode != 0:
            raise RuntimeError(f"fixture command failed: {show([str(a) for a in argv])}\n"
                               f"{decode(proc.stderr).strip()[-500:]}")


def build_fixtures(suite: Suite) -> dict[str, Path]:
    """Every fixture is synthesised by ImageMagick; nothing is read from the user.

    `#404040` is 64/255, so %[fx:mean] has a hand-computable expectation, and only
    PNG keeps EXIF written via `-set` (an eXIf chunk); JPEG silently drops it.
    """
    recipes: list[tuple[str, str, list[str]]] = [
        ("grad", "gradient.png", ["-size", "200x120", "gradient:red-blue"]),
        ("shape", "shape.png", ["-size", "100x100", "xc:none", "-fill", "red",
                                "-draw", "circle 50,50 50,8"]),
        ("photo", "photo.jpg", ["-size", "320x240", "plasma:red-blue", "-quality", "92"]),
        ("anim", "anim.gif", ["-delay", "20", "-size", "80x60", "xc:red", "xc:green", "xc:blue",
                              "-loop", "0"]),
        ("solid", "solid.png", ["-size", "50x50", "xc:#404040"]),
        ("plasma", "plasma.png", ["-size", "100x100", "plasma:fractal"]),
        ("label", "label.png", ["-background", "white", "-fill", "black", "-pointsize", "24",
                                "label:ImageMagick Smoke"]),
        ("gray", "gray.png", ["-size", "40x40", "gradient:black-white", "-colorspace", "Gray"]),
        ("border", "bordered.png", ["-size", "40x30", "xc:red", "-bordercolor", "white", "-border", "20"]),
        ("exif", "exif.png", ["-size", "60x60", "xc:#3060a0", "-set", "exif:Make", "SmokeFixture"]),
        ("small", "small.png", ["-size", "100x80", "xc:orange"]),
    ]
    f: dict[str, Path] = {}
    for key, name, args in recipes:
        f[key] = suite.path(name)
        suite.build(suite.convert(*args, f[key]))
    f["tif"] = suite.path("multi.tif")
    suite.build(suite.convert(f["grad"], f["grad"], f["grad"], f["tif"]))
    return f


def register_cases(suite: Suite, f: dict[str, Path]) -> None:
    out = suite.path
    gs = suite.need_helper("gs", "Ghostscript renders PDF/EPS/PS")
    ffmpeg = suite.need_helper("ffmpeg", "ImageMagick shells out to it for video")

    suite.run("fixtures-synthetic", suite.tool("identify", "-format", "%f %m %wx%h\n",
                                              *[str(p) for p in f.values()]),
              check=lambda c, p: [
                  # identify prints one line per FRAME, so count distinct filenames.
                  c.eq("fixture files decoded",
                       len({line.split()[0] for line in decode(p[-1].stdout).splitlines() if line.strip()}),
                       len(f)),
                  c.eq("gradient geometry", suite.dims(f["grad"]), (200, 120)),
                  c.eq("jpeg geometry", suite.dims(f["photo"]), (320, 240)),
                  c.eq("gif frames", suite.frames(f["anim"]), 3),
                  c.eq("bordered geometry", suite.dims(f["border"]), (80, 70)),
                  c.gt("label: rendered real glyphs",
                       float(suite.fmt(f["label"], "%[standard-deviation]")), 0.0),
                  c.gt("plasma: is textured, not flat",
                       float(suite.fmt(f["plasma"], "%[standard-deviation]")), 0.0)])

    suite.run("resize-exact", suite.convert(f["grad"], "-resize", "100x60", out("resize.png")),
              check=lambda c, p: c.eq("output geometry", suite.dims(out("resize.png")), (100, 60)))

    suite.run("resize-shrink-only-noop", suite.convert(f["small"], "-resize", "400x400>", out("noop.png")),
              check=lambda c, p: c.eq("'>' leaves a smaller image untouched",
                                      suite.dims(out("noop.png")), (100, 80)))

    suite.run("thumbnail-square-fill",
              suite.convert(f["grad"], "-resize", "128x128^", "-gravity", "center",
                            "-extent", "128x128", out("square.png")),
              check=lambda c, p: c.eq("^ + -extent yields an exact square",
                                      suite.dims(out("square.png")), (128, 128)))

    suite.run("crop-with-repage", suite.convert(f["grad"], "-crop", "50x40+30+20", "+repage", out("crop-repage.png")),
              check=lambda c, p: [
                  c.eq("geometry", suite.dims(out("crop-repage.png")), (50, 40)),
                  c.eq("page offset reset", suite.fmt(out("crop-repage.png"), "%X%Y"), "+0+0"),
                  c.eq("page canvas shrunk", suite.fmt(out("crop-repage.png"), "%[page]"), "50x40")])

    # Proves the documented gotcha is real, not folklore.
    suite.run("crop-without-repage-keeps-offset",
              suite.convert(f["grad"], "-crop", "50x40+30+20", out("crop-raw.png")),
              check=lambda c, p: [
                  c.eq("geometry", suite.dims(out("crop-raw.png")), (50, 40)),
                  c.eq("page offset retained", suite.fmt(out("crop-raw.png"), "%X%Y"), "+30+20"),
                  c.eq("page canvas still the original", suite.fmt(out("crop-raw.png"), "%[page]"), "200x120")])

    suite.run("rotate-90-swaps-axes", suite.convert(f["grad"], "-rotate", "90", out("rot.png")),
              check=lambda c, p: c.eq("dimensions swapped", suite.dims(out("rot.png")), (120, 200)))

    suite.run("grayscale-colorspace", suite.convert(f["grad"], "-colorspace", "Gray", out("gray-out.png")),
              check=lambda c, p: [
                  c.eq("colorspace", suite.fmt(out("gray-out.png"), "%[colorspace]"), "Gray"),
                  c.eq("peak saturation", suite.max_saturation(out("gray-out.png")), 0.0),
                  c.eq("grayscale fixture agrees", suite.fmt(f["gray"], "%[colorspace]"), "Gray")])

    suite.run("strip-removes-exif", suite.convert(f["exif"], "-strip", out("stripped.png")),
              check=lambda c, p: [
                  c.true("source carries EXIF", "exif:Make" in suite.fmt(f["exif"], "%[EXIF:*]"),
                         suite.fmt(f["exif"], "%[EXIF:*]").strip()),
                  c.eq("EXIF gone after -strip", suite.fmt(out("stripped.png"), "%[EXIF:*]").strip(), "")])

    suite.run("convert-png-to-jpeg", suite.convert(f["grad"], out("converted.jpg")),
              gate=[suite.need_format("JPEG")],
              check=lambda c, p: [
                  c.eq("output format", suite.fmt(out("converted.jpg"), "%m"), "JPEG"),
                  c.eq("geometry preserved", suite.dims(out("converted.jpg")), (200, 120))])

    suite.run("flatten-removes-alpha", suite.convert(f["shape"], "-background", "white", "-flatten", out("flat.png")),
              check=lambda c, p: [
                  c.eq("source is transparent", suite.fmt(f["shape"], "%A"), "Blend"),
                  c.true("alpha channel gone", suite.fmt(out("flat.png"), "%A") not in ("Blend", "True"),
                         suite.fmt(out("flat.png"), "%A"))])

    suite.run("trim-to-content-box", suite.convert(f["border"], "-trim", "+repage", out("trimmed.png")),
              check=lambda c, p: c.eq("border removed", suite.dims(out("trimmed.png")), (40, 30)))

    suite.run("append-vertical", suite.convert(f["grad"], f["grad"], "-append", out("vstack.png")),
              check=lambda c, p: c.eq("heights summed", suite.dims(out("vstack.png")), (200, 240)))

    suite.run("append-horizontal", suite.convert(f["grad"], f["grad"], "+append", out("hstack.png")),
              check=lambda c, p: c.eq("widths summed", suite.dims(out("hstack.png")), (400, 120)))

    suite.run("gif-coalesce-resize-optimize",
              suite.convert(f["anim"], "-coalesce", "-resize", "40x30", "-layers", "optimize",
                            out("anim-small.gif")),
              gate=[suite.need_format("GIF")],
              check=lambda c, p: [
                  c.eq("frame count preserved", suite.frames(out("anim-small.gif")), 3),
                  c.eq("every frame resized",
                       sorted(set(suite.fmt(out("anim-small.gif"), "%wx%h\n").split())), ["40x30"])])

    suite.run("montage-tile-2x2",
              suite.tool("montage", *[f["grad"]] * 4, "-tile", "2x2", "-geometry", "100x60+0+0",
                         out("montage.png")),
              check=lambda c, p: [
                  c.eq("single output image", suite.frames(out("montage.png")), 1),
                  c.eq("2x2 of 100x60 tiles", suite.dims(out("montage.png")), (200, 120))])

    suite.run("compare-identical-is-zero", suite.tool("compare", "-metric", "AE", f["grad"], f["grad"], "null:"),
              check=lambda c, p: c.eq("absolute error", suite.compare_ae(f["grad"], f["grad"]), 0.0))

    suite.run("compare-different-is-nonzero", suite.tool("compare", "-metric", "AE", f["grad"], f["plasma"], "null:"),
              ok_exits=(0, 1),  # compare returns 1 for "images differ", which is the point here
              check=lambda c, p: c.gt("absolute error", suite.compare_ae(f["grad"], f["plasma"]), 0.0))

    suite.run("jpeg-quality-affects-size", suite.convert(f["plasma"], "-quality", "90", out("q90.jpg")),
              suite.convert(f["plasma"], "-quality", "20", out("q20.jpg")),
              gate=[suite.need_format("JPEG")],
              check=lambda c, p: c.true("q20 smaller than q90",
                                        out("q20.jpg").stat().st_size < out("q90.jpg").stat().st_size,
                                        f"q20={out('q20.jpg').stat().st_size} q90={out('q90.jpg').stat().st_size}"))

    suite.run("jpeg-extent-byte-budget", suite.convert(f["photo"], "-define", "jpeg:extent=8kb", out("budget.jpg")),
              gate=[suite.need_format("JPEG")],
              check=lambda c, p: [
                  c.le("output bytes", out("budget.jpg").stat().st_size, 8 * 1024),
                  c.gt("output not empty", out("budget.jpg").stat().st_size, 0)])

    suite.run("fx-computed-values", suite.tool("identify", "-format", "%[fx:w*h] %[fx:mean]", f["solid"]),
              check=lambda c, p: [
                  c.eq("pixel count 50*50", int(float(decode(p[-1].stdout).split()[0])), 2500),
                  c.near("mean of #404040 is 64/255", float(decode(p[-1].stdout).split()[1]), 64 / 255)])

    font = suite.first_font()
    suite.run("annotate-with-real-font",
              suite.convert("-size", "240x60", "xc:white", "-font", str(font), "-pointsize", "24",
                            "-fill", "black", "-annotate", "+10+40", "Smoke", out("annotated.png")),
              gate=[suite.need(font is not None, "`-list font` reported no fonts")],
              check=lambda c, p: [
                  c.eq("geometry", suite.dims(out("annotated.png")), (240, 60)),
                  c.gt("text actually drawn (not a blank canvas)",
                       float(suite.fmt(out("annotated.png"), "%[standard-deviation]")), 0.0)])

    mog_dir = suite.path("mogrify-out")
    mog_dir.mkdir(exist_ok=True)
    sources = [suite.path("mog-a.png"), suite.path("mog-b.png")]
    shutil.copyfile(f["grad"], sources[0])
    shutil.copyfile(f["small"], sources[1])
    before = [(p.stat().st_size, p.stat().st_mtime_ns) for p in sources]
    suite.run("mogrify-path-is-nondestructive",
              suite.tool("mogrify", "-path", str(mog_dir), "-resize", "50x50", *[str(p) for p in sources]),
              check=lambda c, p: [
                  c.eq("sources untouched (bytes, mtime)",
                       [(q.stat().st_size, q.stat().st_mtime_ns) for q in sources], before),
                  c.eq("source geometry unchanged", suite.dims(sources[0]), (200, 120)),
                  c.eq("outputs written to -path dir", sorted(q.name for q in mog_dir.iterdir()),
                       ["mog-a.png", "mog-b.png"]),
                  c.eq("output resized", suite.dims(mog_dir / "mog-a.png"), (50, 30))])

    suite.run("mpr-register-roundtrip",
              suite.convert(f["grad"], "-write", "mpr:orig", "+delete", "mpr:orig", out("mpr.png")),
              check=lambda c, p: [
                  c.eq("identical to source", suite.compare_ae(f["grad"], out("mpr.png")), 0.0),
                  c.eq("geometry", suite.dims(out("mpr.png")), (200, 120))])

    suite.run("miff-pipe-roundtrip", suite.convert(f["grad"], "miff:-"), suite.convert("miff:-", out("piped.png")),
              pipe=True,
              gate=[suite.need_format("MIFF")],
              check=lambda c, p: [
                  c.gt("intermediate stream non-empty", len(p[0].stdout), 0),
                  c.eq("identical to source", suite.compare_ae(f["grad"], out("piped.png")), 0.0)])

    suite.run("thumbnail-matches-resize", suite.convert(f["grad"], "-thumbnail", "64x64", out("thumb.png")),
              suite.convert(f["grad"], "-resize", "64x64", out("resized64.png")),
              check=lambda c, p: [
                  c.eq("-thumbnail geometry", suite.dims(out("thumb.png")), (64, 38)),
                  c.eq("-resize agrees", suite.dims(out("resized64.png")), suite.dims(out("thumb.png"))),
                  # -thumbnail samples before resampling, so pixels differ slightly and
                  # the encoded file may be LARGER; only the geometry contract holds.
                  c.gt("-thumbnail output is not blank",
                       float(suite.fmt(out("thumb.png"), "%[standard-deviation]")), 0.0)])

    suite.run("tiff-multipage-frames", suite.tool("identify", "-format", "%s %wx%h\n", f["tif"]),
              gate=[suite.need_format("TIFF")],
              check=lambda c, p: [
                  c.eq("frame count", suite.frames(f["tif"]), 3),
                  c.eq("frame indices", [line.split()[0] for line in decode(p[-1].stdout).splitlines()],
                       ["0", "1", "2"])])

    suite.run("webp-roundtrip", suite.convert(f["grad"], out("out.webp")),
              gate=[suite.need_format("WEBP")],
              check=lambda c, p: [
                  c.eq("output format", suite.fmt(out("out.webp"), "%m"), "WEBP"),
                  c.eq("geometry preserved", suite.dims(out("out.webp")), (200, 120))])

    # Gated because -version advertises heic/jxl delegates whose coder modules can
    # be missing from disk; the probe, not the version banner, decides.
    for fmt_name, ext in (("HEIC", "heic"), ("AVIF", "avif"), ("JXL", "jxl")):
        suite.run(f"{ext}-encode", suite.convert(f["grad"], out(f"out.{ext}")),
                  gate=[suite.need_format(fmt_name)],
                  check=lambda c, p, ext=ext: [
                      c.gt("output bytes", out(f"out.{ext}").stat().st_size, 0),
                      c.eq("geometry preserved", suite.dims(out(f"out.{ext}")), (200, 120))])

    pdf_gate = [gs, suite.need_format("PDF")]
    suite.run("pdf-multipage-create", suite.convert(f["grad"], f["small"], out("two.pdf")),
              gate=pdf_gate,
              check=lambda c, p: c.eq("page count", suite.frames(out("two.pdf")), 2))
    suite.run("pdf-rasterize-first-page", suite.convert("-density", "72", f"{out('two.pdf')}[0]", out("page0.png")),
              gate=pdf_gate,
              check=lambda c, p: [
                  c.eq("output format", suite.fmt(out("page0.png"), "%m"), "PNG"),
                  c.eq("geometry at 72dpi", suite.dims(out("page0.png")), (200, 120))])

    suite.run("video-frames-roundtrip", suite.convert(f["anim"], out("clip.mp4")),
              gate=[ffmpeg, suite.need_format("MP4")],
              check=lambda c, p: [
                  c.gt("output bytes", out("clip.mp4").stat().st_size, 0),
                  c.gt("frames decodable", suite.frames(out("clip.mp4")), 0)])

    # ---- negative and safety cases -------------------------------------------
    corrupt = suite.path("corrupt.png")
    corrupt.write_bytes(b"\x89PNG\r\n\x1a\n" + b"garbage-not-a-real-chunk" * 4)
    suite.run("negative-corrupt-input", suite.tool("identify", str(corrupt)),
              expect_failure=True,
              check=lambda c, p: c.true("error mentions the bad file",
                                        corrupt.name in decode(p[-1].stderr), decode(p[-1].stderr).strip()[-200:]))

    suite.run("negative-missing-input", suite.tool("identify", str(suite.path("does-not-exist.png"))),
              expect_failure=True,
              check=lambda c, p: c.true("error is explicit about the missing file",
                                        "unable to open" in decode(p[-1].stderr).lower(),
                                        decode(p[-1].stderr).strip()[-200:]))

    # `label:foo.png` with no such file on disk renders TEXT and exits 0 - a silent
    # wrong answer. An explicit FORMAT: prefix turns it back into a loud failure.
    trap = "label:no-such-file.png"
    suite.run("coder-prefix-neutralized-by-explicit-format", suite.tool("identify", "-format", "%m", trap),
              suite.tool("identify", "-format", "%m", f"PNG:{trap}"),
              expect_failure=True,
              check=lambda c, p: [
                  c.eq("bare name is silently taken as the label coder", decode(p[0].stdout).strip(), "LABEL"),
                  c.eq("bare form exits 0 despite reading no file", p[0].returncode, 0),
                  c.true("PNG: prefix forces a real file read and fails",
                         "unable to open" in decode(p[-1].stderr).lower(), decode(p[-1].stderr).strip()[-200:])])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workdir", type=Path, required=True,
                        help="directory dedicated to generated test artifacts; cleaned on every run")
    parser.add_argument("--verbose", action="store_true")
    parser.add_argument("--report", type=Path, help="where to write the JSON report")
    args = parser.parse_args()

    binary = shutil.which("magick") or shutil.which("convert")
    if not binary:
        print(f"ImageMagick was not found on PATH. Install it from {DOWNLOAD_URL}", file=sys.stderr)
        return 127

    workdir = args.workdir.expanduser().resolve()
    if len(workdir.parts) < 3 or workdir == Path.home():
        print(f"Refusing to use {workdir} as a scratch directory", file=sys.stderr)
        return 2
    if workdir.exists():
        shutil.rmtree(workdir)
    workdir.mkdir(parents=True)

    version_proc = subprocess.run([binary, "-version"], capture_output=True)
    version_text = decode(version_proc.stdout) + decode(version_proc.stderr)
    match = re.search(r"ImageMagick\s+(\d+)\.(\d+)\.(\d+)(?:-(\d+))?", version_text)
    version = match.group(0).replace("ImageMagick ", "") if match else "unknown"
    # IM6's entry point is `convert` and it has no `magick identify` subcommand form.
    im7 = bool(match) and match.group(1) == "7" and Path(binary).name == "magick"

    suite = Suite(binary, workdir, im7, args.verbose)
    try:
        fixtures = build_fixtures(suite)
    except RuntimeError as exc:
        print(str(exc), file=sys.stderr)
        return 3
    register_cases(suite, fixtures)

    if validate_natural_language_cases is None:
        nl_report: dict[str, object] = {
            "ok": None, "reason": "check_natural_language_cases.py not present next to smoke.py"}
    else:
        try:
            nl_report = validate_natural_language_cases(Path(__file__).resolve().parents[1])
        except Exception as exc:
            nl_report = {"ok": False, "reason": f"validator raised: {exc}"}

    counts = {"pass": 0, "fail": 0, "skipped": 0}
    for item in suite.results:
        counts[str(item["status"])] = counts.get(str(item["status"]), 0) + 1
    report = {
        "binary": binary,
        "version": version,
        "im7": im7,
        "workdir": str(workdir),
        "cases": suite.results,
        "summary": counts,
        "natural_language_cases": nl_report,
    }
    report_path = (args.report.expanduser().resolve() if args.report else workdir / "smoke-report.json")
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2))

    if args.verbose:
        for item in suite.results:
            marker = {"pass": "ok  ", "fail": "FAIL", "skipped": "skip"}[str(item["status"])]
            detail = item.get("reason") or "; ".join(str(x) for x in item.get("errors", []))
            print(f"{marker} {item['case']}" + (f" -- {detail}" if detail else ""), file=sys.stderr)
    print(json.dumps({"report": str(report_path), "summary": counts,
                      "natural_language_cases_ok": nl_report.get("ok")}, indent=2))
    return 1 if counts["fail"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
